apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-service
  template:
    metadata:
      labels:
        app: alerting-service
    spec:
      nodeSelector:
        backend: "true"
      imagePullSecrets:
        - name: regcred
      containers:
        - name: alerting-service
          image: eddisonso/alerting-service:latest
          args:
            - "-nats"
            - "nats://nats:4222"
            - "-discord-webhook"
            - "$(DISCORD_WEBHOOK_URL)"
            - "-log-service-grpc"
            - "log-service:50051"
            - "-log-source"
            - "$(POD_NAME)"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-url
                  key: WEBHOOK_URL
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: alerting-service
spec:
  selector:
    app: alerting-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
